# Generated by Django 4.2.1 on 2023-06-01 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_newstype_newsitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('code', models.CharField(max_length=64, verbose_name='код')),
            ],
            options={
                'verbose_name': 'источник новостей',
                'verbose_name_plural': 'источники новостей',
            },
        ),
        migrations.AddField(
            model_name='newsitem',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='app_news.newssource'),
        ),
    ]
