# Generated by Django 4.2.1 on 2023-06-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesale', '0002_alter_home_price_alter_home_square_feet'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
