# Generated by Django 4.2.1 on 2023-06-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesale', '0003_home_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('descriptions', models.TextField(default='')),
                ('published_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
