# Generated by Django 4.2.1 on 2023-06-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesale', '0004_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
    ]
